[package]
name = "cosmic-applet-minimon"
version = "0.4.0"
edition = "2021"
license = "GPL-3.0"

[profile.release]
lto = "thin"
opt-level = 3
debug = false

[dependencies]
i18n-embed-fl = "0.8"
once_cell = "1.19.0"
rust-embed = "8.3.0"
tokio = { version = "1.36.0", features = ["time"] }
sysinfo = "0.33"
serde = "1.0.197"
lazy_static = "1.5"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["applet", "tokio", "wayland", "applet-token"]

[dependencies.i18n-embed]
version = "0.14"
features = ["fluent-system", "desktop-requester"]
